version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT:-8000}:8000
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    restart: on-failure
    command: uvicorn src.presentation.main:app --host 0.0.0.0 --port 8000 --reload